import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AppBar, Toolbar, Typography, Box } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DWS Coding Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    { href: "/", label: "Demo Company" },
    { href: "/about", label: "About" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppBar position="static">
          <Toolbar sx={{ justifyContent: "space-between" }}>
            <Box sx={{ display: "flex", alignItems: "center" }}>
              <Image
                src="/demo-co.png"
                alt="Company Logo"
                width={40}
                height={40}
                style={{ cursor: "pointer" }}
              />
              {links.map((link) => (
                <Link key={link.href} href={link.href} passHref>
                  <Typography
                    variant="h6"
                    component="div"
                    sx={{
                      marginLeft: 2,
                      color: "inherit",
                      textDecoration: "none",
                    }}
                  >
                    {link.label}
                  </Typography>
                </Link>
              ))}
            </Box>
          </Toolbar>
        </AppBar>
        <main>
          <Box sx={{ padding: 3 }}>{children}</Box>
        </main>
      </body>
    </html>
  );
}
