import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { AppBar, Toolbar, Typography, Box } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DWS Coding Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    { href: "/", label: "Home" },
    { href: "/line-chart", label: "Line Chart" },
    { href: "/bar-chart", label: "Bar Chart" },
    { href: "/table", label: "Table" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppBar position="static">
          <Toolbar>
            <Box sx={{ flexGrow: 1, display: "flex", gap: 2 }}>
              {links.map((link) => (
                <Typography
                  key={link.href}
                  variant="h6"
                  component={Link}
                  href={link.href}
                  sx={{
                    color: "inherit",
                    textDecoration: "none",
                    fontWeight: 500,
                  }}
                >
                  {link.label}
                </Typography>
              ))}
            </Box>
          </Toolbar>
        </AppBar>
        <main>
          <Box sx={{ padding: 3 }}>{children}</Box>
        </main>
      </body>
    </html>
  );
}
